# Data & Web Mining
## Python crash course
## Numpy and Pandas


#### Prof. Claudio Lucchese

## NumPy

http://www.numpy.org/

**NumPy** stands for **Numerical Python**.

NumPy is a fundamental package for efficient scientific and numerical computing.

It provides:
- efficient methods for managing arrays and matrices, and operations on them
- several mathematical functions (variance, standard deviation, cumulative sum, ...)
- other: fitting a polynomial, finding the minimum of a function, Fast Fourier Transform, etc.


## Matrix representation and operations

In [3]:
# transform a nested list into a 2D matrix

import numpy as np
a = np.array( [ [1.,2.,3.],
                [4.,5.,6.] ] )

print ("Matrix a:")
print (a)

Matrix a:
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# Element-wise operations
b = a + 2
print ("Matrix b=a+2:")
print (b)
print()

c = a * 7
print ("Matrix c=a*7:")
print (c)
print()

d = b - a
print ("Matrix d=b-a:")
print (d)
print()

e = c / a
print ("Matrix e=c/a:")
print (e)

Matrix b=a+2:
[[3. 4. 5.]
 [6. 7. 8.]]

Matrix c=a*7:
[[ 7. 14. 21.]
 [28. 35. 42.]]

Matrix d=b-a:
[[2. 2. 2.]
 [2. 2. 2.]]

Matrix e=c/a:
[[7. 7. 7.]
 [7. 7. 7.]]


In [5]:
# Matrix transpose and multiplication
z = np.matmul(a, b.T)
print (z)

[[ 26.  44.]
 [ 62. 107.]]


## Mathematical functions

See https://docs.scipy.org/doc/numpy/reference/ufuncs.html for more information.

Let's test `sqrt()` (square root) and `maximum()` (element-wise maximum of two arrays).

In [6]:
a = np.array( [ [1.,2.,3.],[4.,5.,6.] ] )
b = np.array( [ [3.,3.,7.],[1.,1.,2.] ] )

print ("exp function")
print ( np.exp(a))
print ()

print ("element-wise maximum")
print ( np.maximum(a,b) )

exp function
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]

element-wise maximum
[[3. 3. 7.]
 [4. 5. 6.]]


## Aggregation and Statistical methods

Typical `sum`, `mean`, `var`, are available ...

In case of matrices, it is possible to specify the **direction** of the operation.
 - see https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean

In [7]:
m = np.array( [ [1.,2.,3.],
                [4.,5.,6.] ] )

print (m)
print ()

print ("No direction/axis")
print ( np.mean(m) )
print ()

print ("mean over axis 0 (across rows)")
print ( np.mean(m, axis=0) )
print ()

print ("mean over axis 1 (across cols)")
print ( np.mean(m, axis=1) )
print ()


[[1. 2. 3.]
 [4. 5. 6.]]

No direction/axis
3.5

mean over axis 0 (across rows)
[2.5 3.5 4.5]

mean over axis 1 (across cols)
[2. 5.]


## Indexing and Views

It is possible to access elements of matrices/array in a similar way to Python lists.

Slices of a matrix are implemented as **views**, **not copies**, on the original data, sharing the same memory.

In [8]:
m = np.array( [ [1.,2.,3.],
                [4.,5.,6.] ] )

print (m[0,2])
print ()

print ("view/indexing")
view = m[:,1]  # all rows, column with index 1
print ( view )
print ()

print ("modified view and original data")
view[:] = 33
print ( view )
print ()
print ( m )    # also m is modified

3.0

view/indexing
[2. 5.]

modified view and original data
[33. 33.]

[[ 1. 33.  3.]
 [ 4. 33.  6.]]


## Sorting and Fancy Indexing

Similarly to python, the sort method can be used to sort an array or to get a sorted copy.

There is no `key` parameter.

See https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sort.html.

In [9]:
data = np.array([1,-2,3,-4,5])

s = np.sort(data)
print ( "sorted copy    ", s )
print ( "original data  ", data)
print()

data.sort()
print ( "after data.sort()" )
print ( "original data  ", data)

sorted copy     [-4 -2  1  3  5]
original data   [ 1 -2  3 -4  5]

after data.sort()
original data   [-4 -2  1  3  5]


Also sorting may have a direction.

In [10]:
m = np.array( [ [3., 5.,2.],[6., 1.,5.] ] )

print (m)

print ("sort over axis 0 (across rows)")
print ( np.sort(m, axis=0) )
print()

print ("sort over axis 1 (across cols)")
print ( np.sort(m, axis=1) )
print()

print ("flatten and then sort")
print ( np.sort(m, axis=None) )

[[3. 5. 2.]
 [6. 1. 5.]]
sort over axis 0 (across rows)
[[3. 1. 2.]
 [6. 5. 5.]]

sort over axis 1 (across cols)
[[2. 3. 5.]
 [1. 5. 6.]]

flatten and then sort
[1. 2. 3. 5. 5. 6.]


A useful method is `argsort`, which returns the positions of the elements in sorted order, withouth modifying the original array.

The output of `argsort`, can be used in conjuction with fancy indexing.

Example: sort by income and print the corresponding name.

In [11]:
names = np.array([  'Mark', 'Joe', 'Will', 'Bob', 'Jane', 'Carol', 'Donald'])
salaries = np.array([2000,   1200,  3000,  2100,   1580,   1700,    900])

sorted_pos = np.argsort(salaries)
print ("sorted positions", sorted_pos)

print ( "salaries",  salaries[sorted_pos] ) # This is called fancy indexing!
print ( "ages",  names[sorted_pos] ) # This is called fancy indexing!

sorted positions [6 1 4 5 0 3 2]
salaries [ 900 1200 1580 1700 2000 2100 3000]
ages ['Donald' 'Joe' 'Jane' 'Carol' 'Mark' 'Bob' 'Will']


## Optimization

Find the root of a function given it first derivative.

See https://docs.scipy.org/doc/scipy/reference/optimize.html

In [47]:
from scipy import optimize
def f(x):
    return (x**3 - 1)  # only one real root at x = 1

def fprime(x):
    return 3*x**2

sol = optimize.root_scalar( f,                # function
                            x0=0.2,           # initial guess
                            fprime=fprime,    # first derivative
                            method='newton')  # optimization method

print ("The root of the function is:", sol.root)

The root of the function is: 1.0


# More Numpy ?

NumPy deserves your interest, especially for implementing numerical algorithms, matrix-based operations, and to exploit its great algorithms (see also scipy).

From a data perspective, it provides a low level access. We will see the Pandas library, which is more data-oriented and it shares several commonalities with NumPy.

## Pandas: Python Data Analysis Library

See: https://pandas.pydata.org/

Pandas is an open source providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

## A focus  on Series

- **Series** is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called its *index*.

It provides functionalities similar to that of python lists and python dictionaries.

Series have an index. The default index is made by numbers from 0-1, otherwise we can specify it, and we can use arbitrary labels as index.

See https://pandas.pydata.org/docs/reference/api/pandas.Series.html.


In [48]:
import pandas as pd

pds = pd.Series([4, 7, -5, -3])

print(pds)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
pds = pd.Series( [4, 7, -5, -3],
                 index=["George", "John", "Paul", "Ringo"])

# Series my have a name and its index may also have a name
pds.name = "The Beatles"
pds.index.name = "Member"

print(pds)

### Indexing and slicing

Series indexing works analogously to Python list if you want to access by position, or similar to python dictionaries if you want to access by index value.

In [13]:
# access by position
print (pds[2])
print ()

# access by index value
print (pds['Paul'])

NameError: name 'pds' is not defined

In [ ]:
# Fancy indexing by position
print (pds[ [0,3] ])
print ()

# Fancy indexing by index value
p = pds[  ['John', 'Ringo']  ]
print ( p )
print ()

# note: they return pandas series
print (type(p))

In [ ]:
# We also have Boolean Indexing
print (pds[ [True, False, False, True] ])

## Slicing, loc and iloc

Pandas tries to understand whether you are using a position or an index value. (What if they are both integers?)

To avoid confusion, one good recommendation is to use `loc` and `iloc`.

#### Example
As in Python, we can use slicing with positions. **Right extreme is NOT included**.

Recommendation: use `iloc`

In [14]:
print ( pds )
print ()

print ( pds[1:3] )
print ()

print ( pds.iloc[1:3] )
print ()

NameError: name 'pds' is not defined

#### Example
But we can also use slicing with labels. **Right extreme is included**. Index must be sorted !

Recommendation: use `loc`

In [15]:
print ( pds['George':'P'] )     # 'P' is not present
print ()

print ( pds['George':'Paul'] )
print ()

print ( pds.loc['George':'Paul'] )


NameError: name 'pds' is not defined

As for a dictionary you can check for presence.

In [16]:
print("'John' in pds:", "John" in pds )
print("'Mark' in pds:", "Mark" in pds )

# try
# pds["Mark"] # KeyError exception if not present

NameError: name 'pds' is not defined

### Series are mutable

We can change its values with an assignment (also with slicing).

In [17]:
print(pds)
print()

pds['Paul'] = 42

pds['George':'Paul'] = 5

print(pds)

NameError: name 'pds' is not defined

In [ ]:
pds['Gennaro'] = 12 # It's a honor be part of this group

print(pds)

### Filtering + Boolean Indexing

We can filter entries of a Series.

(You have the same in NumPy's Boolean indexing).

#### Example
Here we get only rows with a positive value.

In [18]:
a = pds > 0
print("pds > 0\n", a)
print()

print("pds[ pds > 0]:\n",
       pds[ pds > 0 ]  ) # get only positive values of pds
print("Fab Four are back!")

NameError: name 'pds' is not defined

In [ ]:
# Bye-bye gennaro

psd = pds.drop('Gennaro')

### Operations
We can perform NumPy operations on a Series.

In [ ]:
import numpy as np

print("pds*2:\n", pds*2 )
print()

print("np.exp( pds ):\n", np.exp( pds ) )

### Series from a dictionary

Series are so close to a dictionary that you can create one from a dictionary.

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
pds = pd.Series(sdata)

print(pds)

NameError: name 'pd' is not defined

When passing also an index, this is used to filter matching entries of the dictionary.

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
pds = pd.Series(sdata, index=states) # California is not in sdata

print(pds) # Welcome missing values

NameError: name 'pd' is not defined

Note that `'Utah'` was not included, and that a special value `NaN` is used for the index `California`.

Missing data is common, (e.g., movies withouth ratings), and usually `NaN` is used to represent them.

It is possible to use `isnull` to find null values, and to replace them.

In [21]:
obj = pd.Series({'Ohio': 35000, 'Texas': 71000,
                 'Oregon': 16000, 'Utah': 5000},
               index=['Ohio', 'Texas', 'California'])

print (pd.isnull(obj))
print ()

obj [ pd.isnull(obj) ] = 0.0

print (obj)

NameError: name 'pd' is not defined

Alternatively one can use the `fillna` method.

In [22]:
obj = pd.Series({'Ohio': 35000, 'Texas': 71000,
                 'Oregon': 16000, 'Utah': 5000},
               index=['Ohio', 'Texas', 'California'])

obj2 = obj.fillna(0.0) # returns a new data frame
print (obj)
print ()
print (obj2)

NameError: name 'pd' is not defined

In [ ]:
obj = pd.Series({'Ohio': 35000, 'Texas': 71000,
                 'Oregon': 16000, 'Utah': 5000},
               index=['Ohio', 'Texas', 'California'])

obj.fillna(0.0, inplace=True) # inplace modification
print (obj)

### Allignment by index

A useful Series feature for many applications is that it automatically aligns by index
label in arithmetic operations.

In [ ]:
pds1 = pd.Series({'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000})
                                # California is missing

pds2 = pd.Series({'California': 40000, 'Texas': 555, 'Oregon': 111, 'Utah': 222})
                                # Ohio is missing

pds1 + pds2

In [ ]:
pds1 = pd.Series({'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000})  # California is missing

pds2 = pd.Series({'California': 40000, 'Texas': 555, 'Oregon': 111, 'Utah': 222}) # Ohio is missing

pds1.add(pds2, fill_value=0)

## Let's read a dataset with one line of code!

We can read an excel file!

Data available at http://tennis-data.co.uk/alldata.php.

See: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

Check also the `sheet_name` parameter.

In [23]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'

df = pd.read_excel(dataset_file)
df.head(5) # see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html

ModuleNotFoundError: No module named 'pandas'

In [ ]:
print (type(df))
# see https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

## Dataframe

- **DataFrame** is a 2-dimensional table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.).

See: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

**Features of DataFrame:**
- Mutable
- Potentially columns are of different types
- Labeled axes (rows and columns)
- Can Perform Arithmetic operations on rows and columns

A DataFrame can be seen as a dictionary of columns (indeed, pandas Series), all sharing the same index.

We can ask the number of rows and columns.
We can access index and columns labels with attributes `index`and `column`.

In [24]:
print("df.shape:", df.shape)
print("df.index:", df.index)
print("df.columns:", df.columns)

NameError: name 'df' is not defined

## Question: What is the number of matches?


In [25]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)

print ("Dataframe shape is:", df.shape)
num_matches, num_columns = df.shape
print ("The number of matches is:", num_matches)

ModuleNotFoundError: No module named 'pandas'

### Names

Both index and columns have an attribute `name` to specify their names.


In [26]:
df.index.name   = "Match ID"
df.columns.name = "Features"

df.head()

NameError: name 'df' is not defined

## Statistical summary

We can get a statistical summary for numerical columns.

In [27]:
df.describe()

NameError: name 'df' is not defined

## Data Types

A specific data type is used to store and manage the information in the dataframe. This is important to understand which operations can be performed on the different columns.

Note that also the non-null values are reported. It is not uncommon to have missing values in our dataset.

In [28]:
df.info()

NameError: name 'df' is not defined

## Column selection, addition, and deletion

See: https://pandas.pydata.org/pandas-docs/stable/indexing.html.

Pandas provides several (sometimes confusing) ways to access the columns of a data frame.

#### Example (Selection)
We can select a column by specifying its name.

This operation gives us Pandas Series.

Note that the index is preserved.

In [29]:
a = df["Winner"]

print("a:\n", a)
print("Type: ", type(a))
print()

# Equivalent to

a = df.Winner
print("a:\n", a)
print("Type: ", type(a))

NameError: name 'df' is not defined

You can also select multiple columns. In this case you need to use a list.

Note that the result is a dataframe.

In [30]:
wl = df[ ["Winner","Loser"] ]

wl.head()

NameError: name 'df' is not defined

#### Example (Addition)
We can add a new column by passing a NumPy array (or a list, Pandas Series, and more) or a single number.

In case of a list/array, the length of the array must equal the number of rows (otherwise a ValueError exception is raised)!

In [ ]:
print("df.shape:", df.shape)

         # note that len gives us the number of rows
df['meaning-less']   = np.ones( len(df) )
df['meaning-less-2'] = 2
df['meaning-less-3'] = df['B365W']*2

df.head()

#### Example (Deletion)

Method `drop()` can be used to remove a column. We need to specify axis=1 (axis=0 are the rows).
The built-in `del` can also be used.

`inplace` argument (default is False)  is common in several Pandas' functions that modify the DataFrame.
If True, it says that the function has to modify the DataFrame itself instead of returning a new one.

In [31]:
        # drop returns a new dataframe
df = df.drop('meaning-less', axis=1)
        # unless inplace is set to True
df.drop('meaning-less-2', axis=1, inplace=True)
        # alternative
del df['meaning-less-3']

df.head()

NameError: name 'df' is not defined

## Index

Index does not need to be in integer, and it does not need to be unique.
We can choose one of the column to be the index with function `set_index()`.

Note that the old index is lost!

In [ ]:
df.set_index("Location", inplace=True) # Alternative to df = df.set_index("Location")

# Note the new name of the index
df.head()

## Question: List the tournament names

In [32]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)

df['Tournament']

ModuleNotFoundError: No module named 'pandas'

In [ ]:
set( df['Tournament'] )

You can do this because a pandas Series is iterable, and a python set can be build from any iterable.

You can iterate in two ways.

In [ ]:
for v in df['Tournament']:
    print (v)

In [ ]:
# similar to enumerate
for index,v in df['Tournament'].iteritems():
    print (index, v)

Pandas allows to do better then using python sets.

In [33]:
df['Tournament'].unique()
# see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.unique.html

NameError: name 'df' is not defined

In [ ]:
df['Tournament'].value_counts()
# see: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html

In [ ]:
# Note it returns a Series
for tournament, count in df['Tournament'].value_counts().iteritems():
    print ("During the",tournament, "there were", count, "matches.")

# Question: Find player with most wins

In [ ]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)

winners = df['Winner'].value_counts()
most_winner = winners.index[0]
most_winner

## Question: List the player names, and count the number of matches they had


In [34]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)

players = df['Winner'].value_counts() + df['Loser'].value_counts()
players.sort_values()

ModuleNotFoundError: No module named 'pandas'

In [ ]:
players = df['Winner'].value_counts().add(df['Loser'].value_counts(), fill_value=0)

# Note: you can sort !
players.sort_values(ascending=False)

## Row Selection, Addition, and Deletion

Very similar to column operation , with a different way of specifying rows.

More details at https://pandas.pydata.org/pandas-docs/stable/indexing.html.

#### Example (Selection)
We can access rows by using the index value in the special `loc` attribute.

Note that the result is a dataframe.

In [35]:
df.set_index("Location", inplace=True) # Alternative to df = df.set_index("Location")

df.loc['Brisbane'] # get all the matching rows

NameError: name 'df' is not defined

#### Example (Selection)
We can access rows by using a list of index values.

In [36]:
df.loc[ ['Paris','London'] ]

NameError: name 'df' is not defined

#### Example (Selection)
Rows can be selected by using integer location with the special `iloc` attribute.

In [ ]:
df.iloc[2]

#### Example (Selection)
Slicing over the rows with `iloc`.

In [37]:
df.iloc[0:10]

NameError: name 'df' is not defined

#### Example (Addition)
We can add a new row by using `loc` attribute.

Pandas also has an `append` function (see https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.append.html).

In [ ]:
# Make a smaller copy
small_df = pd.DataFrame( df[ ['Surface', 'Winner', 'Loser'] ] )
small_df = small_df.loc[['London', 'Paris']]

small_df.loc['Mestre'] = ['Clay', 'Claudio L.', 'Nadal R.']
small_df.loc['Mestre'] = ['Clay', 'Claudio L.', 'Federer R.'] # This is a replace

small_df

#### Example (Deletion)
We can remove a row (or more) with `drop()` function.

In [38]:
small_df.drop("Mestre", inplace=True) # axis=0 is the default
small_df

NameError: name 'small_df' is not defined

In [ ]:
# Make a smaller copy
small_df = pd.DataFrame( df[ ['Surface', 'Winner', 'Loser'] ] )
small_df = small_df.loc[['London', 'Paris']]

small_df.loc['Mestre'] = ['Clay', 'Claudio L.', 'Nadal R.']
small_df.loc['Mestre'] = ['Clay', 'Claudio L.', 'Federer R.'] # This is a replace

# Remove all matching rows
small_df.drop(["London", "Paris"], inplace=True)
small_df

### Creating a DataFrame

There are many ways to construct a DataFrame, though one of the most common is from a dictionary of equal-length lists (or NumPy arrays).

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'population': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

df = pd.DataFrame(data)

df.index.name = "Progressive"   # Set index name
df.columns.name = 'Attributes'  # Set columns name

df # Default index is 0...N-1

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'population': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

df = pd.DataFrame(data,
                 index = ['xxx1','xxx2','xxx3','xxx4','xxx5','xxx6'])

df.index.name   = "Custom ID"   # Set index name
df.columns.name = 'Attributes'  # Set columns name

df

## From pandas to numpy

If you prefer working with numpy

In [39]:
m = df.values
print (type(m))
print ()

print (m)

NameError: name 'df' is not defined

# Question: Find the most unexpected win by Nadal with largest odds

In [ ]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'

df = pd.read_excel(dataset_file)

In [ ]:
nadal_winner = df[ df['Winner']=='Nadal R.' ]
nadal_winner = nadal_winner[ ['Winner', 'B365W'] ]
nadal_winner.columns = ['Player','bet'] # see also rename function
nadal_winner.head()

In [ ]:
nadal_winner.sort_values(by='bet',ascending=False, inplace=True)
nadal_winner.head()

In [40]:
match_id = nadal_winner.index[0]
print (df.loc[match_id])

NameError: name 'nadal_winner' is not defined

# Question: how many times the player with the best ranking won the match?


In [ ]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'

df = pd.read_excel(dataset_file)

In [ ]:
df.columns

In [ ]:
w_gt_l = df['WRank'] < df['LRank']

w_gt_l.head()

In [ ]:
w_gt_l = w_gt_l.astype(int)

w_gt_l.head()

In [ ]:
total_wins = w_gt_l.sum()

total_wins

In [ ]:
total_matches, _ = df.shape

total_matches

In [ ]:
print ("The success rate of the best ranked player is", round(100.0*total_wins/total_matches,2), "%" )

# Question: how much would you gain or lose by always betting 10€ on the best ranked player?

In [ ]:
import pandas as pd

dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'

df = pd.read_excel(dataset_file)

In [ ]:
w_gt_l = df['WRank']>df['LRank']

In [ ]:
# decompose the following to understand each singles setps
gains = ( (df['B365W'][w_gt_l]-1.0) * 5.0).sum()

In [ ]:
losses = (~w_gt_l).sum() * 5.0

In [ ]:
total = gains - losses

print ("If always betting on the best ranked, the profit would be", total)

## Additional useful manipulation

Suppose, for some reason, you want to invert name/surname order.

That is, suppose you want to apply the same custom function to every element of a dataframe/series.

In [41]:
def my_fun (x):
    tokens = x.split()
    tokens = tokens[::-1]
    new_x  = ' '.join(tokens)
    return new_x

# note the re-assiggnment
df['Winner'] = df['Winner'].map(my_fun)

df['Winner']

NameError: name 'df' is not defined

## Question: What is the surface with longest matches on average (more games)?

In [ ]:
df.columns

In [ ]:
sub_df = df[ ['W1', 'L1', 'W2', 'L2', 'W3', 'L3', 'W4', 'L4', 'W5', 'L5'] ]
sub_df.head()

In [ ]:
sub_df = sub_df.fillna(0.0)
sub_df.head()

In [ ]:
sub_df.sum()

In [ ]:
sub_df.sum(axis=1)

In [ ]:
df['games'] = sub_df.sum(axis=1)

In [ ]:
df[ ['Surface','games'] ].groupby('Surface').mean()

## Pivot Tables

Similar to groupby, also columsn are grouped.

 - See https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pivot_table.html

The function `pivot_table` has the following main parameters.

| Param name | Description|
|---|:--|
| values  | The column to be aggregated |
| index   | Column names used to create rows of the Pivot Table |
| columns | Column names used to create cols of the Pivot Table  |
| aggfunc | Aggregation function (e.g., `np.sum`)


# Question: Find the most successful player by surface

In [42]:
import pandas as pd
dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)


ModuleNotFoundError: No module named 'pandas'

In [ ]:
df.head()

In [ ]:
import pandas as pd
dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)


df.pivot_table(values="ATP", # irrelevant
               index="Winner",
               columns="Surface",
               aggfunc=len)

In [ ]:
df.pivot_table(values="ATP", # irrelevant
               index="Winner",
               columns="Surface",
               aggfunc=len,
               fill_value=0.0 )

In [ ]:
wins = df.pivot_table(values="ATP", # irrelevant
               index="Winner",
               columns="Surface",
               aggfunc=len,
               fill_value=0.0 )
wins.head()

In [ ]:
wins.columns

In [ ]:
for surface in wins.columns:
    print (wins[surface].sort_values(ascending=False).head(1))
    print ()

# Question: Find the player with the best success rate  by surface

In [ ]:
import pandas as pd
dataset_file = 'http://tennis-data.co.uk/2019/2019.xlsx'
df = pd.read_excel(dataset_file)

In [ ]:
wins = df.pivot_table(values="ATP", # irrelevant
               index="Winner",
               columns="Surface",
               aggfunc=len,
               fill_value=0.0 )
wins.head()

In [ ]:
losses = df.pivot_table(values="ATP", # irrelevant
               index="Loser",
               columns="Surface",
               aggfunc=len,
               fill_value=0.0 )
losses.head()

In [ ]:
total = wins + losses
total.head()

In [ ]:
total = wins.add(losses, fill_value=0)
total.head()

In [ ]:
wins.loc['Nadal R.']

In [ ]:
losses.loc['Nadal R.']

In [ ]:
total.loc['Nadal R.']

In [ ]:
success_rate = wins / total

success_rate.head()

In [ ]:
success_rate = wins / total
success_rate.fillna(0.0, inplace=True)
success_rate.head()

In [ ]:
success_rate.loc['Nadal R.']

In [ ]:
success_rate.loc['Thiem D.']

In [ ]:
for surface in success_rate:  # note: you do not need to use .columns
    print (success_rate[surface].sort_values(ascending=False).head(1))
    print ()

## Other Useful stuff



### DataFrame Joins

#### Many-to-One join
Consider the following two DataFrames.

In [ ]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})

df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})

print(df1)
print(df2)

The data in df1 has multiple rows labeled a and b, whereas df2 has only one row for each value in the key column.

The operation

```
pd.merge(df1, df2, on='key')
```

will produce a merged DataFrame with key the column to join on.


In [43]:
pd.merge(df1, df2, on='key')

NameError: name 'pd' is not defined

Notice that
- data2 of df2 is replicated everywhere key 'a' and 'b' occur in df1
- rows with key 'c' in df1 and 'd' in df2 are not present in df

The latter behavior is called **inner** join: the keys in the result are the intersection, or the common set found in both tables.

Other possible approaches are:
- **left**: keys of left DataFrame are kept
- **right**: keys of right DataFrame are kept
- **outer**: keys of both DataFrames are kept

and can be chosen by setting parameter *how*

#### left

In [44]:
pd.merge(df1, df2, on='key', how='left')

NameError: name 'pd' is not defined

#### right

In [ ]:
pd.merge(df1, df2, on='key', how='right')

#### outer

In [45]:
pd.merge(df1, df2, on='key', how='outer')

NameError: name 'pd' is not defined

#### Many-to-Many join
Many-to-many merges happens when the same key has more than one occurrence in both DataFrames.

Many-to-many joins form the Cartesian product of the rows having the same key.

See the following example:

In [46]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a',  'a', 'b'],
                    'data1': range(5)})

df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                    'data2': range(5)})

print (df1)
print()
print (df2)
print ()

pd.merge(df1, df2, on='key', how='left')

NameError: name 'pd' is not defined

Note that, since there were three 'b' rows in df1 and two in df2, there are six 'b' rows in the result.

The merge can be performed also respect to more than one variable. To determine which key combinations will appear in the result depending on the choice of merge method, **think of the multiple keys as forming an array of tuples** to be used as a single join key.

# References

 - **Python for Data Analysis**. O'Reilly. Wes McKinney.
   - Section 5.1 (Indexing, Selection, and Filtering)
   - Section 5.2 (Arithmetic and Data Alignment Function Application and Mapping Sorting and Ranking)
   - Section 5.3 (Unique Values, Value Counts, and Membership)
   - Section 10.4 (Pivot Tables)
   - Section 14.5
   - https://github.com/wesm/pydata-book
